import { randomUUID } from 'node:crypto';
import { HASH_A, HASH_B, createEvidence, createUserAndCase, expectRejected, prisma } from './db';

// Behavioural checks for the DB-enforced invariants of docs/03-DATABASE-SCHEMA.md §22
// (Doc 14 Gate B; Doc 15 DB-01–DB-30, VW-01/02, SEQ-01).

afterAll(async () => {
  await prisma.$disconnect();
});

/** evidence → parse result → page 1 → line 1, the minimum provenance chain for an extraction. */
async function createParsedLine(caseId: string, evidenceId: string, text = 'Pay to demo@upi') {
  const parse = await prisma.parseResult.create({
    data: {
      caseId,
      evidenceId,
      parserKind: 'IMAGE_OCR',
      engine: 'test-engine',
      engineVersion: '0',
      status: 'SUCCEEDED',
      pageCount: 1,
    },
  });
  await prisma.sourcePage.create({ data: { parseResultId: parse.id, caseId, pageNumber: 1 } });
  const line = await prisma.sourceLine.create({
    data: { caseId, parseResultId: parse.id, evidenceId, pageNumber: 1, lineNumber: 1, text },
  });
  return { parse, line };
}

function extractionData(caseId: string, evidenceId: string, parseResultId: string) {
  return {
    caseId,
    evidenceId,
    parseResultId,
    fieldType: 'UPI_ID' as const,
    rawValue: 'demo@upi',
    normalizedValue: 'demo@upi',
    normalizationStatus: 'NORMALIZED' as const,
    method: 'RULE' as const,
    confidence: 0.9,
    confidenceBasis: 'SOURCE_VALIDATION' as const,
    confidenceBand: 'HIGH' as const,
    snippet: 'Pay to demo@upi',
  };
}

describe('case reference (SEQ-01)', () => {
  it('is generated by the database as CF-<sequence>', async () => {
    const a = await createUserAndCase();
    const b = await prisma.case.create({ data: { userId: a.user.id } });
    expect(a.kase.caseReference).toMatch(/^CF-\d{5,}$/);
    const n = (ref: string) => Number(ref.slice(3));
    expect(n(b.caseReference)).toBe(n(a.kase.caseReference) + 1);
    expect(n(a.kase.caseReference)).toBeGreaterThanOrEqual(10001);
  });

  it('restricts deleting a user who owns cases', async () => {
    const { user } = await createUserAndCase();
    await expectRejected(prisma.user.delete({ where: { id: user.id } }), /cases_user_id_fkey/);
  });
});

describe('evidence limits (G-4) — at the limit accepted, one over rejected', () => {
  it('caps a case at 20 items via sequence_no', async () => {
    const { kase } = await createUserAndCase();
    await createEvidence(kase.id, 20);
    await expectRejected(createEvidence(kase.id, 21), /evidence_items_sequence_no_check/);
    await expectRejected(createEvidence(kase.id, 20), /Unique constraint/);
  });

  it('accepts 10,485,760 bytes and rejects 10,485,761', async () => {
    const { kase } = await createUserAndCase();
    await createEvidence(kase.id, 1, { byteSize: 10_485_760n });
    await expectRejected(
      createEvidence(kase.id, 2, { byteSize: 10_485_761n }),
      /evidence_items_byte_size_check/,
    );
    await expectRejected(
      createEvidence(kase.id, 3, { byteSize: 0n }),
      /evidence_items_byte_size_check/,
    );
  });

  it('accepts 40,000,000 px and rejects 40,000,001 px', async () => {
    const { kase } = await createUserAndCase();
    await createEvidence(kase.id, 1, { imageWidth: 8000, imageHeight: 5000 });
    await expectRejected(
      createEvidence(kase.id, 2, { imageWidth: 40_000_001, imageHeight: 1 }),
      /evidence_items_image_dimensions_check/,
    );
  });

  it('accepts a 20-page PDF and rejects 21 pages', async () => {
    const { kase } = await createUserAndCase();
    const pdf = {
      evidenceType: 'PDF' as const,
      detectedContentType: 'application/pdf',
      originalFilename: 'receipt.pdf',
      imageWidth: null,
      imageHeight: null,
    };
    await createEvidence(kase.id, 1, { ...pdf, pageCount: 20 });
    await expectRejected(
      createEvidence(kase.id, 2, { ...pdf, pageCount: 21 }),
      /evidence_items_page_count_check/,
    );
  });

  it('accepts 20,000 pasted characters and rejects 20,001', async () => {
    const { kase } = await createUserAndCase();
    const paste = {
      evidenceType: 'TEXT' as const,
      pasteKind: 'MESSAGE' as const,
      detectedContentType: 'text/plain',
      originalFilename: null,
      imageWidth: null,
      imageHeight: null,
    };
    await createEvidence(kase.id, 1, { ...paste, textCharCount: 20_000 });
    await expectRejected(
      createEvidence(kase.id, 2, { ...paste, textCharCount: 20_001 }),
      /evidence_items_text_char_count_check/,
    );
  });

  it('rejects an unsupported detected content type once uploaded', async () => {
    const { kase } = await createUserAndCase();
    await expectRejected(
      createEvidence(kase.id, 1, { detectedContentType: 'image/webp' }),
      /evidence_items_detected_content_type_check/,
    );
  });
});

describe('evidence state and fingerprint', () => {
  it('derives evidence_ref from sequence_no', async () => {
    const { kase } = await createUserAndCase();
    const item = await createEvidence(kase.id, 4);
    expect(item.evidenceRef).toBe('E04');
  });

  it('allows UPLOADING rows without a fingerprint and requires one afterwards', async () => {
    const { kase } = await createUserAndCase();
    await prisma.evidenceItem.create({
      data: {
        caseId: kase.id,
        sequenceNo: 1,
        evidenceType: 'PNG',
        originalFilename: 'a.png',
        storageKey: `test/${randomUUID()}`,
      },
    });
    await expectRejected(
      createEvidence(kase.id, 2, { sha256: null, uploadedAt: null }),
      /evidence_items_sha256_check/,
    );
  });

  it('makes sha256 immutable once set (INV-E5)', async () => {
    const { kase } = await createUserAndCase();
    const item = await createEvidence(kase.id, 1);
    await expectRejected(
      prisma.evidenceItem.update({ where: { id: item.id }, data: { sha256: HASH_B } }),
      /sha256 is immutable/,
    );
  });

  it('never allows a retryable PDF_NO_TEXT_LAYER failure (OD-03, INV-E7)', async () => {
    const { kase } = await createUserAndCase();
    const failed = {
      evidenceType: 'PDF' as const,
      detectedContentType: 'application/pdf',
      originalFilename: 'scan.pdf',
      imageWidth: null,
      imageHeight: null,
      pageCount: 2,
      processingStatus: 'FAILED' as const,
      failureCode: 'PDF_NO_TEXT_LAYER' as const,
    };
    await createEvidence(kase.id, 1, { ...failed, failureRetryable: false });
    await expectRejected(
      createEvidence(kase.id, 2, { ...failed, failureRetryable: true }),
      /evidence_items_pdf_no_text_layer_check/,
    );
  });

  it('computes has_usable_text_layer from the OD-03 ten-character rule', async () => {
    const { kase } = await createUserAndCase();
    const item = await createEvidence(kase.id, 1);
    const parse = await prisma.parseResult.create({
      data: {
        caseId: kase.id,
        evidenceId: item.id,
        parserKind: 'PDF_TEXT_LAYER',
        engine: 'test',
        engineVersion: '0',
        status: 'SUCCEEDED',
        pageCount: 2,
      },
    });
    await prisma.sourcePage.createMany({
      data: [
        { parseResultId: parse.id, caseId: kase.id, pageNumber: 1, nonWhitespaceCharCount: 9 },
        { parseResultId: parse.id, caseId: kase.id, pageNumber: 2, nonWhitespaceCharCount: 10 },
      ],
    });
    const pages = await prisma.sourcePage.findMany({
      where: { parseResultId: parse.id },
      orderBy: { pageNumber: 'asc' },
    });
    expect(pages.map((p) => p.hasUsableTextLayer)).toEqual([false, true]);
  });
});

describe('case isolation (INV-C2, INV-P3)', () => {
  it('rejects a child row that references a parent in another case', async () => {
    const a = await createUserAndCase();
    const b = await createUserAndCase();
    const evidenceA = await createEvidence(a.kase.id, 1);
    await expectRejected(
      prisma.parseResult.create({
        data: {
          caseId: b.kase.id,
          evidenceId: evidenceA.id,
          parserKind: 'IMAGE_OCR',
          engine: 'test',
          engineVersion: '0',
          status: 'SUCCEEDED',
          pageCount: 1,
        },
      }),
      /parse_results_evidence_id_case_id_fkey/,
    );
  });

  it('rejects provenance that points into another case', async () => {
    const a = await createUserAndCase();
    const b = await createUserAndCase();
    const evidenceA = await createEvidence(a.kase.id, 1);
    const eventB = await prisma.timelineEvent.create({
      data: {
        caseId: b.kase.id,
        eventKey: `k-${randomUUID()}`,
        eventType: 'OTHER',
        timestampPrecision: 'INFERRED_ORDER_ONLY',
        sortOrder: 1,
        description: 'Event',
        confidence: 0.5,
        confidenceBand: 'LOW',
        origin: 'AI_GENERATED',
      },
    });
    // Owner in case B, target evidence in case A.
    await expectRejected(
      prisma.factSource.create({
        data: {
          caseId: b.kase.id,
          timelineEventId: eventB.id,
          refKind: 'EVIDENCE',
          evidenceId: evidenceA.id,
          ordinal: 1,
        },
      }),
      /fact_sources_evidence_id_case_id_fkey/,
    );
  });
});

describe('extraction and provenance', () => {
  it('rejects method USER (INV-X3) and non-source identifier confidence (INV-X4)', async () => {
    const { kase } = await createUserAndCase();
    const item = await createEvidence(kase.id, 1);
    const { parse } = await createParsedLine(kase.id, item.id);
    const base = extractionData(kase.id, item.id, parse.id);
    await prisma.extraction.create({ data: base });
    await expectRejected(
      prisma.extraction.create({ data: { ...base, method: 'USER' } }),
      /extractions_method_not_user_check/,
    );
    await expectRejected(
      prisma.extraction.create({ data: { ...base, confidenceBasis: 'MODEL_JUDGEMENT' } }),
      /extractions_identifier_basis_check/,
    );
  });

  it('detaches extractions from a deleted entity without touching case_id', async () => {
    const { kase } = await createUserAndCase();
    const item = await createEvidence(kase.id, 1);
    const { parse } = await createParsedLine(kase.id, item.id);
    const entity = await prisma.entity.create({
      data: {
        caseId: kase.id,
        entityType: 'UPI_ID',
        canonicalValue: 'demo@upi',
        maskedValue: 'de**@upi',
      },
    });
    const extraction = await prisma.extraction.create({
      data: { ...extractionData(kase.id, item.id, parse.id), entityId: entity.id },
    });
    await prisma.entity.delete({ where: { id: entity.id } });
    const after = await prisma.extraction.findUniqueOrThrow({ where: { id: extraction.id } });
    expect(after.entityId).toBeNull();
    expect(after.caseId).toBe(kase.id);
  });

  it('enforces exactly one owner per fact source and de-duplicates links (NULLS NOT DISTINCT)', async () => {
    const { user, kase } = await createUserAndCase();
    const entity = await prisma.entity.create({
      data: {
        caseId: kase.id,
        entityType: 'BANK_OR_WALLET',
        canonicalValue: 'Example Bank',
        maskedValue: 'Example Bank',
        isUserStated: true,
      },
    });
    const statement = await prisma.userStatement.create({
      data: {
        caseId: kase.id,
        authorUserId: user.id,
        statementKind: 'FOLLOW_UP_ANSWER',
        subject: 'finding:x',
        valueText: 'Example Bank',
      },
    });
    const link = {
      caseId: kase.id,
      entityId: entity.id,
      refKind: 'USER_STATEMENT' as const,
      userStatementId: statement.id,
      ordinal: 1,
    };
    await prisma.factSource.create({ data: link });
    await expectRejected(prisma.factSource.create({ data: link }), /Unique constraint/);
    await expectRejected(
      prisma.factSource.create({
        data: {
          caseId: kase.id,
          refKind: 'USER_STATEMENT',
          userStatementId: statement.id,
          ordinal: 1,
        },
      }),
      /fact_sources_owner_arc_check/,
    );
  });
});

describe('timeline (INV-X5)', () => {
  it('requires a time unless the event is order-only', async () => {
    const { kase } = await createUserAndCase();
    const event = {
      caseId: kase.id,
      eventKey: `k-${randomUUID()}`,
      eventType: 'CALL' as const,
      timestampPrecision: 'EXACT' as const,
      sortOrder: 1,
      description: 'Call',
      confidence: 0.7,
      confidenceBand: 'MEDIUM' as const,
      origin: 'AI_GENERATED' as const,
    };
    await expectRejected(
      prisma.timelineEvent.create({ data: event }),
      /timeline_events_event_at_check/,
    );
    await prisma.timelineEvent.create({
      data: { ...event, timestampPrecision: 'INFERRED_ORDER_ONLY' },
    });
  });

  it('keeps original_* immutable after the first correction', async () => {
    const { user, kase } = await createUserAndCase();
    const statement = await prisma.userStatement.create({
      data: {
        caseId: kase.id,
        authorUserId: user.id,
        statementKind: 'CORRECTION',
        subject: 'timeline_event:x',
        valueText: '12:07',
      },
    });
    const event = await prisma.timelineEvent.create({
      data: {
        caseId: kase.id,
        eventKey: `k-${randomUUID()}`,
        eventType: 'CALL',
        eventAt: new Date('2026-01-01T06:35:00Z'),
        timestampPrecision: 'APPROXIMATE',
        sortOrder: 1,
        description: 'Call',
        confidence: 0.7,
        confidenceBand: 'MEDIUM',
        origin: 'AI_GENERATED',
      },
    });
    await prisma.timelineEvent.update({
      where: { id: event.id },
      data: {
        correctionStatus: 'USER_CORRECTED',
        originalEventType: 'CALL',
        originalEventAt: event.eventAt,
        originalTimestampPrecision: 'APPROXIMATE',
        originalDescription: 'Call',
        correctionStatementId: statement.id,
        eventAt: new Date('2026-01-01T06:37:00Z'),
        timestampPrecision: 'EXACT',
      },
    });
    await expectRejected(
      prisma.timelineEvent.update({
        where: { id: event.id },
        data: { originalEventAt: new Date('2026-01-01T06:00:00Z') },
      }),
      /immutable after the first correction/,
    );
  });
});

describe('analysis, signals and urgency', () => {
  async function createRun(caseId: string, status: 'QUEUED' | 'RUNNING' | 'SUCCEEDED' = 'QUEUED') {
    return prisma.analysisRun.create({
      data: { caseId, kind: 'ANALYSIS', trigger: 'USER_START', status },
    });
  }

  it('allows only one QUEUED/RUNNING run per case (INV-Q1)', async () => {
    const { kase } = await createUserAndCase();
    const first = await createRun(kase.id);
    await expectRejected(createRun(kase.id), /Unique constraint/);
    await prisma.analysisRun.update({ where: { id: first.id }, data: { status: 'SUCCEEDED' } });
    await createRun(kase.id, 'RUNNING');
  });

  it('allows only one primary scam signal per case (INV-S1)', async () => {
    const { kase } = await createUserAndCase();
    const run = await createRun(kase.id, 'RUNNING');
    const step = await prisma.agentStep.create({
      data: { runId: run.id, caseId: kase.id, stepName: 'SCAM_ANALYSIS', sequenceNo: 1 },
    });
    const signal = {
      caseId: kase.id,
      agentStepId: step.id,
      confidence: 0.8,
      confidenceBand: 'MEDIUM' as const,
      explanation: 'Signals consistent with…',
    };
    await prisma.scamSignal.create({
      data: { ...signal, label: 'KYC_IMPERSONATION', isPrimary: true },
    });
    await prisma.scamSignal.create({ data: { ...signal, label: 'PHISHING', isPrimary: false } });
    await expectRejected(
      prisma.scamSignal.create({ data: { ...signal, label: 'UPI_FRAUD', isPrimary: true } }),
      /Unique constraint/,
    );
  });

  it('enforces the G2-v1 urgency rule and one current assessment (INV-U1, INV-U3)', async () => {
    const { kase } = await createUserAndCase();
    const assessment = (level: 'HIGH' | 'MEDIUM' | 'LOW', u1: boolean, u2: boolean) => ({
      caseId: kase.id,
      ruleVersion: 'G2-v1',
      level,
      signalU1FinancialLoss: u1,
      signalU2CredentialExposure: u2,
      explanationText: 'Urgency is …',
      disclaimerText: 'Urgency shows how soon to act …',
      templateParams: {},
      isCurrent: false,
    });
    await expectRejected(
      prisma.urgencyAssessment.create({ data: assessment('HIGH', false, true) }),
      /urgency_assessments_g2_v1_check/,
    );
    await expectRejected(
      prisma.urgencyAssessment.create({ data: assessment('LOW', false, true) }),
      /urgency_assessments_g2_v1_check/,
    );
    await prisma.urgencyAssessment.create({ data: assessment('MEDIUM', false, true) });
    await prisma.urgencyAssessment.create({
      data: { ...assessment('HIGH', true, true), isCurrent: true },
    });
    await expectRejected(
      prisma.urgencyAssessment.create({
        data: { ...assessment('LOW', false, false), isCurrent: true },
      }),
      /Unique constraint/,
    );
  });
});

describe('missing information', () => {
  it('keeps the identity document informational with no question (INV-M1)', async () => {
    const { kase } = await createUserAndCase();
    const item = {
      caseId: kase.id,
      findingKey: 'MISSING_FIELD:IDENTITY_DOCUMENT',
      findingKind: 'MISSING_FIELD' as const,
      checklistField: 'IDENTITY_DOCUMENT' as const,
      checklistVariant: 'FINANCIAL' as const,
      reasonText: 'Keep ready',
      isHighValue: false,
    };
    await expectRejected(
      prisma.missingInformationItem.create({ data: item }),
      /identity_document_check/,
    );
    await prisma.missingInformationItem.create({ data: { ...item, status: 'INFORMATIONAL' } });
  });
});

describe('reports, review and export (R-1)', () => {
  async function generatedReport(caseId: string, userId: string, versionNumber: number) {
    return prisma.report.create({
      data: {
        caseId,
        versionNumber,
        status: 'GENERATED',
        schemaVersion: '1',
        content: { sections: [] },
        contentSha256: HASH_A,
        pdfStorageKey: `reports/${randomUUID()}`,
        pdfSha256: HASH_B,
        requestedBy: userId,
        generatedAt: new Date(),
      },
    });
  }

  it('binds an export to a confirmation of the same report version (INV-R4)', async () => {
    const { user, kase } = await createUserAndCase();
    const v1 = await generatedReport(kase.id, user.id, 1);
    const v2 = await generatedReport(kase.id, user.id, 2);
    const confirmV1 = await prisma.reviewConfirmation.create({
      data: { caseId: kase.id, reportId: v1.id, reportContentSha256: HASH_A, confirmedBy: user.id },
    });
    const exportData = {
      caseId: kase.id,
      reviewConfirmationId: confirmV1.id,
      format: 'ZIP_BUNDLE' as const,
      requestedBy: user.id,
    };
    await prisma.export.create({ data: { ...exportData, reportId: v1.id } });
    await expectRejected(
      prisma.export.create({ data: { ...exportData, reportId: v2.id } }),
      /exports_review_confirmation_id_report_id_fkey/,
    );
  });

  it('allows one active confirmation per version and requires a void reason', async () => {
    const { user, kase } = await createUserAndCase();
    const v1 = await generatedReport(kase.id, user.id, 1);
    const confirmation = {
      caseId: kase.id,
      reportId: v1.id,
      reportContentSha256: HASH_A,
      confirmedBy: user.id,
    };
    const first = await prisma.reviewConfirmation.create({ data: confirmation });
    await expectRejected(
      prisma.reviewConfirmation.create({ data: confirmation }),
      /Unique constraint/,
    );
    await expectRejected(
      prisma.reviewConfirmation.update({ where: { id: first.id }, data: { voidedAt: new Date() } }),
      /review_confirmations_void_check/,
    );
    await prisma.reviewConfirmation.update({
      where: { id: first.id },
      data: { voidedAt: new Date(), voidReason: 'CASE_CHANGED' },
    });
    await prisma.reviewConfirmation.create({ data: confirmation });
  });

  it('keeps invalidated versions without content (INV-R5)', async () => {
    const { user, kase } = await createUserAndCase();
    const v1 = await generatedReport(kase.id, user.id, 1);
    await expectRejected(
      prisma.report.update({
        where: { id: v1.id },
        data: {
          status: 'INVALIDATED',
          invalidatedAt: new Date(),
          invalidationReason: 'EVIDENCE_DELETED',
        },
      }),
      /reports_generated_content_check|reports_invalidation_check/,
    );
  });
});

describe('integrity verification (INV-V1)', () => {
  it('ties the result to the hashes and never reports an unreadable object as a mismatch', async () => {
    const { user, kase } = await createUserAndCase();
    const item = await createEvidence(kase.id, 1);
    const base = {
      caseId: kase.id,
      evidenceId: item.id,
      requestedBy: user.id,
      recordedSha256: HASH_A,
    };
    await prisma.integrityVerification.create({
      data: { ...base, computedSha256: HASH_A, result: 'MATCH' },
    });
    await prisma.integrityVerification.create({
      data: { ...base, computedSha256: HASH_B, result: 'MISMATCH' },
    });
    await prisma.integrityVerification.create({
      data: { ...base, result: 'COULD_NOT_COMPLETE', failureCode: 'OBJECT_MISSING' },
    });
    await expectRejected(
      prisma.integrityVerification.create({
        data: { ...base, computedSha256: HASH_B, result: 'MATCH' },
      }),
      /integrity_verifications_result_check/,
    );
    await expectRejected(
      prisma.integrityVerification.create({ data: { ...base, result: 'MISMATCH' } }),
      /integrity_verifications_result_check/,
    );
  });
});

describe('audit log (INV-A3)', () => {
  it('is append-only for the application role', async () => {
    const entry = await prisma.auditLog.create({
      data: { actorKind: 'SYSTEM', action: 'CASE_CREATED', outcome: 'SUCCEEDED' },
    });
    await expectRejected(
      prisma.auditLog.update({ where: { id: entry.id }, data: { outcome: 'FAILED' } }),
      /permission denied|append-only/,
    );
    await expectRejected(
      prisma.auditLog.delete({ where: { id: entry.id } }),
      /permission denied|append-only/,
    );
  });

  it('accepts only the action vocabulary and a user id iff the actor is a user', async () => {
    await expectRejected(
      prisma.auditLog.create({
        data: { actorKind: 'SYSTEM', action: 'SOMETHING_ELSE', outcome: 'SUCCEEDED' },
      }),
      /audit_logs_action_check/,
    );
    await expectRejected(
      prisma.auditLog.create({
        data: { actorKind: 'USER', action: 'CASE_CREATED', outcome: 'SUCCEEDED' },
      }),
      /audit_logs_actor_check/,
    );
  });
});

describe('deletion and views', () => {
  it('cascades case deletion to case-owned rows while audit rows survive (OD-11)', async () => {
    const { kase } = await createUserAndCase();
    const item = await createEvidence(kase.id, 1);
    await createParsedLine(kase.id, item.id);
    await prisma.auditLog.create({
      data: { caseId: kase.id, actorKind: 'SYSTEM', action: 'CASE_DELETED', outcome: 'SUCCEEDED' },
    });
    await prisma.case.delete({ where: { id: kase.id } });
    expect(await prisma.evidenceItem.count({ where: { caseId: kase.id } })).toBe(0);
    expect(await prisma.sourceLine.count({ where: { caseId: kase.id } })).toBe(0);
    expect(await prisma.auditLog.count({ where: { caseId: kase.id } })).toBe(1);
  });

  it('derives entity_evidence_links and case_overview (VW-01, VW-02)', async () => {
    const { kase } = await createUserAndCase();
    const e1 = await createEvidence(kase.id, 1);
    const e2 = await createEvidence(kase.id, 2, { processingStatus: 'PROCESSING' });
    const entity = await prisma.entity.create({
      data: {
        caseId: kase.id,
        entityType: 'UPI_ID',
        canonicalValue: 'demo@upi',
        maskedValue: 'de**@upi',
      },
    });
    for (const item of [e1, e2]) {
      const { parse } = await createParsedLine(kase.id, item.id);
      // Two extractions from E01 still yield one link row (DISTINCT).
      await prisma.extraction.create({
        data: { ...extractionData(kase.id, item.id, parse.id), entityId: entity.id },
      });
      if (item === e1) {
        await prisma.extraction.create({
          data: { ...extractionData(kase.id, item.id, parse.id), entityId: entity.id },
        });
      }
    }

    const links = await prisma.$queryRaw<{ evidence_id: string }[]>`
      SELECT evidence_id FROM entity_evidence_links WHERE entity_id = ${entity.id}::uuid ORDER BY evidence_id`;
    expect(links.map((l) => l.evidence_id).sort()).toEqual([e1.id, e2.id].sort());

    const [overview] = await prisma.$queryRaw<
      {
        evidence_total: number;
        evidence_processed: number;
        evidence_uploaded: number;
        evidence_processing: number;
        urgency_level: string | null;
        has_active_confirmation: boolean;
        entity_counts: Record<string, number>;
      }[]
    >`SELECT * FROM case_overview WHERE case_id = ${kase.id}::uuid`;
    expect(overview).toMatchObject({
      evidence_total: 2,
      evidence_uploaded: 1,
      evidence_processing: 1,
      evidence_processed: 0,
      urgency_level: null,
      has_active_confirmation: false,
      entity_counts: { UPI_ID: 1 },
    });
  });

  it('marks a current urgency assessment out of date before ACTIONS_READY (03 §14.4)', async () => {
    const { kase } = await createUserAndCase();
    await prisma.urgencyAssessment.create({
      data: {
        caseId: kase.id,
        ruleVersion: 'G2-v1',
        level: 'LOW',
        signalU1FinancialLoss: false,
        signalU2CredentialExposure: false,
        explanationText: 'Urgency is LOW …',
        disclaimerText: 'Urgency shows how soon to act …',
        templateParams: {},
      },
    });
    const read = async () =>
      (
        await prisma.$queryRaw<{ urgency_out_of_date: boolean }[]>`
        SELECT urgency_out_of_date FROM case_overview WHERE case_id = ${kase.id}::uuid`
      )[0]?.urgency_out_of_date;
    expect(await read()).toBe(true);
    await prisma.case.update({ where: { id: kase.id }, data: { status: 'ACTIONS_READY' } });
    expect(await read()).toBe(false);
  });
});
